#! /usr/bin/env bash

# Plot the distribution of created messages from *_CreatedMessagesReport.sh 
# generated by the ONE simulator

if [ -z $1 ]
then
	echo "usage: $0 <*_CreatedMessagesReport.txt>"
	exit
fi
inFile=$1
filePrefix=$(echo $inFile | cut -f 1 -d '.')


# the format of CreatedMessagesReport likes this:
:<<BLOCK
# time  ID  size  fromHost  toHost  TTL  isResponse
32.0000 M1 8834 n32 n9 1440 N 
58.0000 M2 7273 n16 n52 1440 N 
84.0000 M3 8122 n21 n9 1440 N
BLOCK

# create a tmp file
tmp_inFile="/tmp/ti_tmp.$$"   #to store after deleting the first line of inFile
trap "rm -f $tmp_inFile" EXIT

##################################################################

### Step 1: delete the fisrt line ###
sed -e "1d" $inFile > $tmp_inFile

fileSource=${filePrefix}_source.txt
fileSink=${filePrefix}_sink.txt
filePairwise=${filePrefix}_pairwise.txt
outFigure=${filePrefix}.png

### Step 2: statistics ###
cut -f 4 -d ' ' $tmp_inFile 	| sed "s/n//g" | sort -n 		| uniq -c > $fileSource		#remove Group.groupID = n
cut -f 5 -d ' ' $tmp_inFile 	| sed "s/n//g" | sort -n 		| uniq -c > $fileSink		#remove Group.groupID = n
cut -f 4-5 -d ' ' $tmp_inFile 	| sed "s/n//g" | sort -k1,1n -k2,2n	| uniq -c > $filePairwise	#remove Group.groupID = n


totalMsg=$(wc -l $tmp_inFile | cut -f 1 -d ' ')
totalHosts=$(wc -l $fileSource | cut -f 1 -d ' ')
#avgMsg=$(echo "$totalMsg*1.0/$totalHosts"|bc)  # it does not work
avgMsg=$(awk -v totalMsg=$totalMsg -v totalHosts=$totalHosts 'BEGIN {printf "%.2f\n", totalMsg/totalHosts}')


### Step 3: plot the data ###

tmp_pltFile="/tmp/pf_tmp.$$"   
trap "rm -f $tmp_pltFile" EXIT


## use here document to create plot file
cat<<'EOF' > $tmp_pltFile
set style line 1 pt 1 lw 1
set style line 2 pt 2 lw 1
set style line 3 pt 3 lw 1


set term png
set out outFigure
set grid 
set key box
set key bottom right 


set xrang [0:xMax]
#set xtics nomirror 0,10,xMax
set mxtics 10

set arrow from 0, average to xMax, average nohead lc rgb 'blue'  #average number of messages
#set label "average" at 0, average


set xlabel 'node ID'
set ylabel '#messages'
set title 'Created Messages Distribution'

plot	f1 	using 2:1 ls 2 title 'Source',\
	f2 	using 2:1 ls 1 title 'Sink'
EOF

### Step 4: plot and open png file ###
gnuplot -e "f1 = '${fileSource}'; f2 = '${fileSink}'; outFigure = '${outFigure}'; average = '${avgMsg}'; xMax=$((totalHosts-1))" $tmp_pltFile
xdg-open $outFigure
 
